apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    freaks.service: postservice
  name: postservice-db
  namespace: freaks
spec:
  replicas: 1
  selector:
    matchLabels:
      freaks.service: postservice
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        freaks.service: postservice
    spec:
      containers:
      - args:
        - --default-authentication-plugin=mysql_native_password
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: freaksPSWD
        - name: "MYSQL_DATABASE"
          value: "PostDb"
        - name: MYSQL_USER
          value: root
        image: mysql
        imagePullPolicy: "IfNotPresent"
        name: postservice-db
        ports:
        - containerPort: 3306
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: postservice-db-data
      hostname: postservice-db
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: postservice-db-data
        persistentVolumeClaim:
          claimName: postservice-db-data
status: {}