apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postservice-db-data
  namespace: freaks
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}